language: php
php:
  - '7.1'
  - '7.2'
  - nightly
env:
  - SYMFONY_VERSION="4.0.*"
  - SYMFONY_VERSION="4.1.*"

install:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer install
script: vendor/bin/phpspec run
