language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.1.*"
  - SYMFONY_VERSION="3.2.*"
  - SYMFONY_VERSION="3.3.*"
  - SYMFONY_VERSION="3.4.*"
  - SYMFONY_VERSION="4.0.*"
install: 
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer install
script: vendor/bin/phpspec run
