language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
env:
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.1.*"
  - SYMFONY_VERSION="3.2.*"
install: 
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer install
script: vendor/bin/phpspec run
